apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cats-dep
  name: cats-web-deployment
spec:
  selector:
    matchLabels:
      app: cats
  replicas: 3
  template:
    metadata:
      labels:
        app: cats
      name: cats-web
    spec:
      containers:
      - image: 632981034191.dkr.ecr.us-east-1.amazonaws.com/ddogra1-labs-cats:CATS_57e905a07a3a79ed780876d98c021486c87f7fe4
        name: cats
        resources: {}
        ports:
          - containerPort: 80