apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: dogs-rep
  name: dogs-web-replicas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
      name: dogs-web
    spec:
      containers:
      - image: 632981034191.dkr.ecr.us-east-1.amazonaws.com/ddogra1-labs-dogs:DOGS_57e905a07a3a79ed780876d98c021486c87f7fe4
        name: dogs
        resources: {}
        ports:
          - containerPort: 80